name: airflow
channels:
- defaults
dependencies:
- python=3.7.3
- pip:
  - apache-airflow[postgres, password, crypto]==1.10.4
  - pyYAML==5.3
  - psycopg2-binary==2.7.5
  - sqlalchemy==1.3.8
  - slackclient==1.2.1
  - Werkzeug==0.16.1
  - confluent-kafka==1.3.0
  - dacite==1.2.0
  - oss2==2.9.1
  - google-cloud-storage
